ARG UV_VERSION=0.8.14
ARG PYTHON_VERSION=3.13
ARG VARIANT=bookworm
FROM ghcr.io/astral-sh/uv:${UV_VERSION} AS uv

FROM python:${PYTHON_VERSION}-${VARIANT} AS base

COPY --link --from=uv /uv /uvx /usr/local/bin/

ARG UV_PROJECT_ENVIRONMENT=/opt/uv/venv
ENV PATH=${UV_PROJECT_ENVIRONMENT}/bin:$PATH \
    PYTHONUNBUFFERED=1 \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_NO_EDITABLE=1 \
    UV_NO_INSTALL_PROJECT=1 \
    UV_PROJECT_ENVIRONMENT=${UV_PROJECT_ENVIRONMENT} \
    UV_PYTHON_DOWNLOADS=never \
    VIRTUAL_ENV=${UV_PROJECT_ENVIRONMENT} \
    VIRTUAL_ENV_PROMPT=''

RUN mkdir -p ${UV_PROJECT_ENVIRONMENT}
WORKDIR /usr/src/app
