name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  UV_VERSION: 0.8.12
  GHCR_IMAGE_REPOSITORY: ghcr.io/${{ github.repository }}
  PLATFORMS: linux/amd64,linux/arm64/v8

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        variant:
          - bookworm
          - bookworm-slim
          - trixie
          - trixie-slim
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-qemu-action@v3.6.0
        with:
          platforms: ${{ env.PLATFORMS }}
      - uses: docker/setup-buildx-action@v3.11.1
      - uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: ${{ env.GHCR_IMAGE_REPOSITORY }}:${{ github.sha }}-${{ matrix.python }}-${{ matrix.variant }}
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            POETRY_VERSION=${{ env.UV_VERSION }}
            PYTHON_VERSION=${{ matrix.python }}
            VARIANT=${{ matrix.variant }}
