name: Release

on:
  release:
    types: [published]

env:
  UV_VERSION: 0.8.14
  GHCR_IMAGE_REPOSITORY: ghcr.io/${{ github.repository }}
  PLATFORMS: linux/amd64,linux/arm64/v8

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        variant:
          - bookworm
          - trixie
        include:
          - python: "3.13"
            is_default_python: true
          - variant: trixie
            is_default_variant: true
    env:
      GIT_SHA_TAG: ${{ env.GHCR_IMAGE_REPOSITORY }}:${{ github.sha }}-${{ matrix.python }}-${{ matrix.variant }}
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: tag ${{ matrix.python }}-${{ matrix.variant }}
        run: docker buildx imagetools create --tag ${{ env.GHCR_IMAGE_REPOSITORY }}:${{ matrix.python }}-${{ matrix.variant }} $GIT_SHA_TAG

      - if: matrix.is_default_variant
        name: tag for default variant (${{ matrix.python }})
        run: docker buildx imagetools create --tag ${{ env.GHCR_IMAGE_REPOSITORY }}:${{ matrix.python }} $GIT_SHA_TAG  

      - if: matrix.is_default_python
        name: tag for default python (${{ matrix.variant }})
        run: docker buildx imagetools create --tag ${{ env.GHCR_IMAGE_REPOSITORY }}:${{ matrix.variant }} $GIT_SHA_TAG
      
      - if: matrix.is_default_python && matrix.is_default_variant
        name: tag for default python and variant (latest)
        run: docker buildx imagetools create --tag ${{ env.GHCR_IMAGE_REPOSITORY }}:latest $GIT_SHA_TAG
