name: Release

on:
  release:
    types: [published]

env:
  UV_VERSION: 0.8.14
  PLATFORMS: linux/amd64,linux/arm64/v8

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        variant:
          - bookworm
          - trixie
        include:
          - python: "3.13"
            is_default_python: true
          - variant: trixie
            is_default_variant: true
    env:
      GIT_SHA_TAG: ${{ github.sha }}-${{ matrix.python }}-${{ matrix.variant }}

    steps:
      - uses: actions/checkout@v4.1.4
      - uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: tag ${{ matrix.python }}-${{ matrix.variant }}
        uses: ./.github/actions/tag
        with:
          source: ${{ env.GIT_SHA_TAG }}
          target: ${{ matrix.python }}-${{ matrix.variant }}

      - if: matrix.is_default_variant
        name: tag ${{ matrix.python }} (default variant)
        uses: ./.github/actions/tag
        with:
          source: ${{ env.GIT_SHA_TAG }}
          target: ${{ matrix.python }}

      - if: matrix.is_default_python
        name: tag ${{ matrix.variant }} (default python)
        uses: ./.github/actions/tag
        with:
          source: ${{ env.GIT_SHA_TAG }}
          target: ${{ matrix.variant }}
      
      - if: matrix.is_default_python && matrix.is_default_variant
        name: tag latest (default python and variant)
        uses: ./.github/actions/tag
        with:
          source: ${{ env.GIT_SHA_TAG }}
          target: latest
